sudo: false

language: python
 
python:
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install coveralls
 
script:
    - python -Wall setup.py test -a "--cov ngo --cov-report term-missing"

after_success:
    - coveralls