sudo: false

language: python
 
python:
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install pytest pytest-cov coveralls
 
script:
    - py.test --cov=./

after_success:
  - coveralls